default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: gogodiary_dev

test:
  <<: *default
  database: gogodiary_test

production:
  <<: *default
  database: gogodiary_production
